"""HTML period-close report generator and controller notification."""

from __future__ import annotations

import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

_REPORT_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "reports")

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Period Close Report — {period_name} Ledger {ledger_id}</title>
<style>
  body {{ font-family: Arial, sans-serif; margin: 40px; color: #1a1a1a; }}
  h1 {{ color: #1e3a5f; border-bottom: 2px solid #1e3a5f; padding-bottom: 8px; }}
  h2 {{ color: #2c5282; margin-top: 32px; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 12px; }}
  th {{ background: #1e3a5f; color: white; padding: 8px 12px; text-align: left; }}
  td {{ padding: 7px 12px; border-bottom: 1px solid #e2e8f0; }}
  tr:nth-child(even) {{ background: #f7fafc; }}
  .badge-ok {{ background: #c6f6d5; color: #276749; border-radius: 4px; padding: 2px 8px; font-size: 0.85em; }}
  .badge-warn {{ background: #fefcbf; color: #744210; border-radius: 4px; padding: 2px 8px; font-size: 0.85em; }}
  .badge-err {{ background: #fed7d7; color: #9b2c2c; border-radius: 4px; padding: 2px 8px; font-size: 0.85em; }}
  .kpi-grid {{ display: flex; gap: 20px; flex-wrap: wrap; margin: 16px 0; }}
  .kpi {{ background: #edf2f7; border-radius: 8px; padding: 16px 24px; min-width: 160px; }}
  .kpi-val {{ font-size: 2em; font-weight: bold; color: #1e3a5f; }}
  .kpi-label {{ font-size: 0.85em; color: #4a5568; margin-top: 4px; }}
  .footer {{ margin-top: 48px; font-size: 0.8em; color: #718096; border-top: 1px solid #e2e8f0; padding-top: 16px; }}
</style>
</head>
<body>
<h1>Oracle Fusion Cloud — Period-Close Package</h1>
<p><strong>Ledger ID:</strong> {ledger_id} &nbsp;|&nbsp;
   <strong>Period:</strong> {period_name} &nbsp;|&nbsp;
   <strong>Generated:</strong> {generated_at}</p>

<div class="kpi-grid">
  <div class="kpi"><div class="kpi-val">{subledger_count}</div><div class="kpi-label">Subledgers Closed</div></div>
  <div class="kpi"><div class="kpi-val">{unbalanced_count}</div><div class="kpi-label">Unresolved Journals</div></div>
  <div class="kpi"><div class="kpi-val">{ic_imbalances}</div><div class="kpi-label">IC Imbalances</div></div>
  <div class="kpi"><div class="kpi-val">{variance_flags}</div><div class="kpi-label">Variance Flags</div></div>
</div>

<h2>Subledger Close Status</h2>
{subledger_table}

<h2>GL Journal Resolution</h2>
{journal_section}

<h2>Intercompany Elimination</h2>
{ic_section}

<h2>Trial Balance</h2>
{tb_section}

<h2>Variance Analysis</h2>
{variance_section}

<h2>Open Items for Controller</h2>
{open_items_section}

<div class="footer">
Generated by Oracle Period-Close Orchestration Agent &mdash;
<a href="https://github.com/karthikchundi-commits/oracle-period-close-agent">
github.com/karthikchundi-commits/oracle-period-close-agent</a>
</div>
</body>
</html>
"""


def _badge(ok: bool, ok_text: str = "OK", warn_text: str = "Action Required") -> str:
    cls = "badge-ok" if ok else "badge-err"
    return f'<span class="{cls}">{ok_text if ok else warn_text}</span>'


def _subledger_table(subledger_status: list[dict]) -> str:
    if not subledger_status:
        return "<p>No subledger data available.</p>"
    rows = "".join(
        f"<tr><td>{s.get('application_name','')}</td>"
        f"<td>{s.get('close_status','Unknown')}</td>"
        f"<td>{s.get('transfer_status','Unknown')}</td>"
        f"<td>{_badge(s.get('close_status') == 'Closed')}</td></tr>"
        for s in subledger_status
    )
    return (
        "<table><tr><th>Subledger</th><th>Close Status</th>"
        "<th>Transfer Status</th><th></th></tr>"
        f"{rows}</table>"
    )


def _variance_table(flags: list[dict]) -> str:
    if not flags:
        return "<p>No accounts exceed the variance threshold.</p>"
    rows = "".join(
        f"<tr><td>{f.get('account','')}</td>"
        f"<td>{f.get('account_description','')}</td>"
        f"<td>${f.get('current_period_net',0):,.2f}</td>"
        f"<td>${f.get('prior_period_net',0):,.2f}</td>"
        f"<td>{f.get('variance_pct',0):.1f}%</td>"
        f"<td>{f.get('flag_reason','')}</td></tr>"
        for f in flags[:20]
    )
    return (
        "<table><tr><th>Account</th><th>Description</th>"
        "<th>Current</th><th>Prior</th><th>Variance%</th><th>Reason</th></tr>"
        f"{rows}</table>"
    )


def generate_close_report(ledger_id: int, period_name: str, close_summary: dict) -> str:
    os.makedirs(_REPORT_DIR, exist_ok=True)

    subledger_status = close_summary.get("subledger_status", [])
    unbalanced = not close_summary.get("unbalanced_journals_resolved", True)
    ic_clear = close_summary.get("intercompany_clear", True)
    tb_balanced = close_summary.get("trial_balance_balanced", False)
    variance_flags = close_summary.get("variance_flags", [])

    open_items = []
    if unbalanced:
        open_items.append("Unresolved GL journal imbalances require corrective entries before close.")
    if not ic_clear:
        open_items.append("Intercompany elimination entries required — see IC section.")
    if not tb_balanced:
        open_items.append("Trial balance is not balanced — do not close GL period until resolved.")
    for vf in variance_flags[:5]:
        open_items.append(
            f"Variance flag: {vf.get('account','')} — {vf.get('flag_reason','')} "
            f"(${vf.get('variance_amount',0):,.2f})"
        )

    open_items_html = (
        "<ul>" + "".join(f"<li>{item}</li>" for item in open_items) + "</ul>"
        if open_items else "<p>No open items. Ready for controller sign-off.</p>"
    )

    html = _HTML_TEMPLATE.format(
        ledger_id=ledger_id,
        period_name=period_name,
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        subledger_count=sum(1 for s in subledger_status if s.get("close_status") == "Closed"),
        unbalanced_count="0" if not unbalanced else "Pending",
        ic_imbalances="0" if ic_clear else "Yes",
        variance_flags=len(variance_flags),
        subledger_table=_subledger_table(subledger_status),
        journal_section=(
            '<p><span class="badge-ok">Resolved</span> All journals balanced.</p>'
            if not unbalanced else
            '<p><span class="badge-err">Action Required</span> Unbalanced journals exist.</p>'
        ),
        ic_section=(
            '<p><span class="badge-ok">Clear</span> No intercompany imbalances.</p>'
            if ic_clear else
            '<p><span class="badge-err">Action Required</span> Intercompany imbalances require elimination entries.</p>'
        ),
        tb_section=(
            '<p><span class="badge-ok">Balanced</span> Total DR = Total CR.</p>'
            if tb_balanced else
            '<p><span class="badge-warn">Unverified</span> Trial balance not yet confirmed.</p>'
        ),
        variance_section=_variance_table(variance_flags),
        open_items_section=open_items_html,
    )

    filename = f"close_report_{ledger_id}_{period_name.replace('-', '_')}.html"
    path = os.path.join(_REPORT_DIR, filename)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(html)
    return path


def request_controller_signoff(
    notification_settings: Any,
    ledger_id: int,
    period_name: str,
    report_path: str,
    summary: str,
    urgency: str = "NORMAL",
) -> bool:
    subject = (
        f"[{'URGENT - ' if urgency == 'HIGH' else ''}Period Close] "
        f"Ledger {ledger_id} — {period_name} Close Package Ready for Sign-Off"
    )
    body_html = f"""\
<h2>Oracle Fusion Cloud — Period-Close Sign-Off Request</h2>
<p><strong>Ledger:</strong> {ledger_id} &nbsp;|&nbsp; <strong>Period:</strong> {period_name}</p>
<p><strong>Urgency:</strong> {urgency}</p>
<hr>
<pre style="font-family:monospace;background:#f7fafc;padding:16px;">{summary}</pre>
<hr>
<p><strong>Close Report:</strong> {report_path}</p>
<p>Please review the attached close package and approve the GL period closure.</p>
<p style="font-size:0.8em;color:#718096;">
Generated by Oracle Period-Close Orchestration Agent &mdash;
github.com/karthikchundi-commits/oracle-period-close-agent
</p>
"""
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = notification_settings.from_email
        msg["To"] = notification_settings.controller_email
        msg.attach(MIMEText(body_html, "html"))

        with smtplib.SMTP(notification_settings.smtp_host, notification_settings.smtp_port) as smtp:
            smtp.ehlo()
            smtp.starttls()
            smtp.send_message(msg)
        return True
    except Exception:
        return False
